version: 2.1

jobs:
  build:
    parameters:
      env:
        default: "prod"
        type: enum
        enum: ["prod", "dev"]
    docker:
      - image: circleci/node
    steps:
      - run: mkdir -p dist
      - run: echo "<< parameters.env >>" > dist/a.txt
      - run: mkdir -p ~/tmp/workspace/<< parameters.env >>
      - run: cp -r dist/ ~/tmp/workspace/<< parameters.env >>/
      - persist_to_workspace:
          root: ~/tmp/workspace/<< parameters.env >>
          paths:
            - dist
  deploy:
    parameters:
      env:
        default: "prod"
        type: enum
        enum: ["prod", "dev"]
    docker:
      - image: circleci/node
    steps:
      - attach_workspace:
          at: ~/tmp/workspace/<< parameters.env >>
      - run: cp -r ~/tmp/workspace/<< parameters.env >>/dist/ ./
      - run: cat dist/a.txt

workflows:
  build-test:
    jobs:
      - build:
         env: prod
         name: build-prod
      - build:
         env: dev
         name: build-dev

      - deploy:
          env: prod
          name: deploy-prod
          requires:
            - build-prod
      - deploy:
          env: dev
          name: deploy-dev
          requires:
            - build-dev
